version: "3.9"
services:
  bookingdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: bookingdb
    ports:
      - "6870:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
  booking-backend:
    build: ./booking-api
    image: booking-api
    container_name: booking-backend
    platform: linux/amd64
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:1234567890@bookingdb:5432/bookingdb?schema=public
      - PORT=3500
      # - DATABASE_URL=postgresql://root:WXkf1IzJrqmvF3kiVUUtkfbq1YbGq14g@dpg-cvn17r7gi27c73beoba0-a.oregon-postgres.render.com/ecusolarcharge
    ports:
      - "4600:3500"

networks:
  postgres:
